# Thông tin chung
group=UNNM
group_full=Unanimous
show=Summer Ghost
short=SGhost

# Thông tin codec
format=BDRip 1080p
vcodec=AVC
acodec=FLAC
codec_info=${format} ${vcodec} ${acodec}

vtrack=AVC @ Vanilla
atrack=FLAC 2.0 @ 3069 kb/s

# Thông tin file output
title=[${group}] ${show} (${codec_info})
muxdir=[${group}] ${show} (${codec_info})
muxout=muxdir/${title} [${mux.crc}].mkv
ncmuxout=${muxdir}/Creditless/${muxout}

# Raws và Font
raw=raws/${short}*.mkv
fonts=fonts

# Thông tin về file sub
dialogue=${episode}/${short} - Dialogue.ass
extra=${episode}/${short} - Extra.ass
TS=${episode}/${short} - TS*.ass
INS=${episode}/${short} - INS*.ass

# Số tập
episodes={01..01}

# Creditless
ncs=NCOP{1..2}|NCED{1..2}
ncsubs=${short}_${episode}.ass
ncraw=raws/${short} - ${episode}*.mkv